- name: Install the Horizon (Pre-requisite)
  apt:
    name:
      - openstack-dashboard
    state: present
    update_cache: yes

- name: Configure the Horizon
  copy:
    dest: /etc/openstack-dashboard/local_settings.py
    content: |
      CACHES = {
          'default': {
              'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache', 'LOCATION': 192.168.56.124:11211',
              },
              }
      SESSION_ENGINE = "django.contrib.sessions.backends.cache"
      OPENSTACK_HOST = "192.168.56.124"
      OPENSTACK_KEYSTONE_URL = "http://%s/identity/v3" % OPENSTACK_HOST
      OPENSTACK_KEYSTONE_URL = "http://192.168.56.124:5000/v3"

      TIME_ZONE = "Asia/Tokyo"

      OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True
      OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = 'Default'
      OPENSTACK_API_VERSIONS = {
          "identity": 3,
          "volume": 3,
          "compute": 2,
      }
      WSGIApplicationGroup %{GLOBAL}

- name: Install the Apache2
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Reload the apache2
  shell: sudo systemctl reload apache2.service
